### ISSUE TITLE
Proposed Change: Move power input closer to heatbed terminals

### ISSUE THREAD

**Issue by boelle** [Flydroid/Teensy-3DPC#2]
the closer the input terminals are to output the better

while on terminals make sure they can handle about 15A just to be on the safe side

and for FET's pick ones that has as low on resistance as possible, it will make them run cooler

**Comment by Flydroid** [comment]
I'm a bit on and off with the development as I have some other projects at the same time and currently no 3D Printer which needs a new board. I love the Teensy boards and a 3D printer controller is still missing in its repertoire, so I wanted to design a board using modern features like TMC2130 and still be kind of cost effective. As I realized this might not be the case with a 25-30$ MCU and 10$ stepper boards, i was a bit conflicted with the overall design decision to use so many daughter boards.

The mosfet design is based on the Duet WIFI, which I trust has made very good design choices. 
Another thing I looking for input is fusing? I have seen the automotive fuses on ramps boards - I generally would put the fuses beside the PCB using standard fuse holders.

**Comment by boelle** [comment]
the automotive fuses are a great idea... the RADDS board for the DUE board uses them too

i think tom sanladerer  said they are far better than the standard poly fuses

since you are at the beginning try and go for the mini fuses

as for the cost... i would pick your design over the duet or smoothie for the simple reason that i can change out a stepper driver if i blown one

i can do the same with the duet, but i will be forced to use an external driver and it will clutter things
