### ISSUE TITLE
IDEA: Support analog probes

### ISSUE THREAD

**Issue by boelle** [Flydroid/Teensy-3DPC#3]
since we have a fast cpu it might make a bit sense to support analog probes like the mini ir touch sensor

https://miscsolutions.wordpress.com/mini-height-sensor-board/

it can be debated if it makes it any better, but my argument would be that an analog value can be used to make a more precise detection. in some cases you have to make the probing speed slower. this depends on how fast the cpu can cope with the analog voltage and move the stepper at the same time

while on probes make sure to include at least one servo connector so probes like bl touch can be used

**Comment by Flydroid** [comment]
That just the feedback I need! I was still figuring out which features the board should support and which pins are needed. As the bottom pins of the 3.5/3.6 are a bit hard to reach I'm not sure yet if i will include them. Probably some testing is needed. 
Generally want to route out every available pin.

**Comment by boelle** [comment]
i'm good at getting ideas, but i lack the skill of creating them

i can do basic layout in eagle but other than that i'm a noob :-D

if you can route a pin and its not in use at least make a hole where people can solder in a wire or put in a single pin header thingy
