### ISSUE TITLE
Proposed Change: add a 2nd Z endstop input

### ISSUE THREAD

**Issue by boelle** [Flydroid/Teensy-3DPC#4]
this is just if there are enough spare pins and it does not make it harder to route tracks

the point is that the printer can automatic sync individual Z steppers if they have an endstop each

one could say that some of the not used endstops can be used for this

this of course puts up the next question, what are the max endstops used for on a 3d printer? i have never seen max endstops used

i'm building a hypercube evolution and it has max endstops on X and Y but i have a hard time to figure what they are good for

**Comment by Flydroid** [comment]
Yes, usually 3D Printers only have one end stop for each axis for a repeatable definite position from which every thing is referenced.
Even if you have several Z steppers, aren't they connected mechanically and thus only on end stop is needed?

**Comment by boelle** [comment]
no, not excatly

i'm building this one: https://www.thingiverse.com/thing:2254103

the version to the right on the  picture has 2 z steppers and they can get out of sync

also printers like prusa i3 have 2 z steppers but connected to same stepper driver. 

my idea is to have each stepper motor on individual stepper drivers and each stepper motor has it own endstop. 

With repetier firmware (and marlin too i think) when you send G28 Z both steppers go to endstop, but if one Z stepper homes a little before the other it will stop

when both are homed they will be in sync

hope it made sense??

**Comment by Flydroid** [comment]
I have not really experience with 2 steppers but isn't the Z Platform so rigid that even if there would be two endstops beside each motor, they would activate at the same time?
