### ISSUE TITLE
IDEA: Base layout on RAMPS 1.4.2

### ISSUE THREAD

**Issue by boelle** [Flydroid/Teensy-3DPC#5]
Not sure if you like the idea but i was boared and thought if it would not be faster to base the board partly on the Ramps 1.4.2

http://reprap.org/wiki/RAMPS_1.4#RAMPS_1.4.2

i could try and have a go at it starting by adding a way to connect the teensy to it instead of a mega board

thoughts?

**Comment by boelle** [comment]
so far i have managed to replace the std. stepsticks with 2130 ones (Y and Z pending)

i have not included the spi bus yet as i want to judge how easy it would be

**Comment by Flydroid** [comment]
You could do that, but wiring in the Teensy is just as much work as starting out fresh. You could use parts of the ramps design for example the heater mosfet schematic. 

Or did you want to put the Teensy on a breakout for the MEGA layout -> https://forum.pjrc.com/threads/36244-Teensy-3-5-3-6-Breakout-board-to-test-things-with?p=142487&viewfull=1#post142487?
Then you could just use the ramps with a Teensy, but no special TMC2130 functions if you don't redo the RAMPS board aswell.

**Comment by boelle** [comment]
hmm... will have to thinker a bit 

thanks for the input... food for thought

**Comment by boelle** [comment]
have asked for the sources for that teensy breakout

and during the morning i have partly reworked the ramps board so now it has tmc2130 sockets, just need to figure how to do the spi bus...

i'm open to that you are right that it might be faster to do from scratch

**Comment by boelle** [comment]
i got the spi added to except the CS lines

so from your org list i have:

- Dual automotive fuses

- LCD Addon compatible

what i miss are:

- check that everything can work with 3.3 level signal

- add endstop input protection

- figure how to add CS lines

- pt100/thermocouple


there are allready caps on the endstop input's but i assume that you are thinking reverse connection projection?
